version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: book-library-test
    command: mvn test
    volumes:
      - maven_cache:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: test

volumes:
  maven_cache: