# Development environment values
replicaCount: 1

image:
  pullPolicy: Always

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: dev-book-library.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: dev-book-library-tls
      hosts:
        - dev-book-library.example.com

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

app:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "dev,kubernetes"
    - name: SERVER_PORT
      value: "8080"
    - name: SPRING_JPA_SHOW_SQL
      value: "true"
    - name: LOG_LEVEL
      value: "DEBUG"

postgresql:
  enabled: true
  auth:
    postgresPassword: "devpostgres"
    username: "devuser"
    password: "devpass"
    database: "devbookdb"
  persistence:
    size: 1Gi