# Staging environment values
replicaCount: 2

image:
  pullPolicy: Always

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
    - host: staging-book-library.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: staging-book-library-tls
      hosts:
        - staging-book-library.example.com

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

app:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "staging,kubernetes"
    - name: SERVER_PORT
      value: "8080"
    - name: SPRING_JPA_SHOW_SQL
      value: "false"
    - name: LOG_LEVEL
      value: "INFO"

postgresql:
  enabled: true
  auth:
    postgresPassword: "stagingpostgres"
    username: "staginguser"
    password: "stagingpass"
    database: "stagingbookdb"
  persistence:
    size: 5Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80