name: CD - Deploy to Dev

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Docker image tag to deploy'
        required: false
        type: string

env:
  ENVIRONMENT: dev
  NAMESPACE: book-library-dev
  RELEASE_NAME: book-library-dev

jobs:
  deploy:
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get image tag
      id: image-tag
      run: |
        if [ -n "${{ github.event.inputs.image-tag }}" ]; then
          echo "tag=${{ github.event.inputs.image-tag }}" >> $GITHUB_OUTPUT
        else
          echo "tag=dev-$(date +'%Y%m%d')-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        fi

    - name: Deploy with Helm
      uses: ./.github/actions/helm-deploy
      with:
        release-name: ${{ env.RELEASE_NAME }}
        namespace: ${{ env.NAMESPACE }}
        environment: ${{ env.ENVIRONMENT }}
        image-tag: ${{ steps.image-tag.outputs.tag }}
        kubeconfig: ${{ secrets.KUBECONFIG_DEV }}
        dry-run: 'false'

    - name: Create deployment record
      uses: actions/github-script@v7
      with:
        script: |
          const deployment = await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha,
            environment: 'development',
            description: 'Deployed to dev environment',
            auto_merge: false,
            required_contexts: [],
            payload: {
              image_tag: '${{ steps.image-tag.outputs.tag }}',
              namespace: '${{ env.NAMESPACE }}'
            }
          });
          
          await github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: deployment.data.id,
            state: 'success',
            environment_url: 'https://dev-book-library.example.com',
            description: 'Deployment successful'
          });

    - name: Notify Slack
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: |
          Dev Deployment ${{ job.status }}
          Image: ${{ steps.image-tag.outputs.tag }}
          Environment: ${{ env.ENVIRONMENT }}
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}