name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [dev, staging]

# Add permissions for the workflow
permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: gwynbliedd/book-library

jobs:
  setup-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && github.event.action != 'closed'
    outputs:
      release-name: ${{ steps.preview.outputs.release-name }}
      namespace: ${{ steps.preview.outputs.namespace }}
      short-sha: ${{ steps.short-sha.outputs.sha }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Generate preview namespace
      id: preview
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        NAMESPACE="book-library-pr-${PR_NUMBER}"
        RELEASE_NAME="book-library-pr-${PR_NUMBER}"
        echo "namespace=${NAMESPACE}" >> $GITHUB_OUTPUT
        echo "release-name=${RELEASE_NAME}" >> $GITHUB_OUTPUT

    - name: Setup Java and Maven
      uses: ./.github/actions/setup-java-maven
      with:
        java-version: '17'

    - name: Build application
      run: mvn clean package -DskipTests

    - name: Set short SHA
      id: short-sha
      run: echo "sha=$(echo ${{ github.sha }} | cut -c1-8 )" >> $GITHUB_OUTPUT
      
    - name: Build and Push Docker Image
      id: docker-build
      uses: ./.github/actions/docker-build-push
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image-name: ${{ env.IMAGE_NAME }}
        push: true
        extra-tags: pr-${{ github.event.pull_request.number }}-${{ steps.short-sha.outputs.sha }}

  deploy-preview:
    name: Deploy PR Preview
    runs-on: self-hosted
    needs: setup-preview
    if: github.event.pull_request.draft == false && github.event.action != 'closed'
    
    steps:
    - name: Debug message
      run: |
        echo "Runner OS: $RUNNER_OS"
        echo "Runner arch: $RUNNER_ARCH"
        which helm
        which kubectl
        kubectl version --client

    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy PR Preview
      uses: ./.github/actions/helm-deploy
      with:
        release-name: ${{ needs.setup-preview.outputs.release-name }}
        namespace: ${{ needs.setup-preview.outputs.namespace }}
        environment: dev
        image-tag: pr-${{ github.event.pull_request.number }}-${{ needs.setup-preview.outputs.short-sha }}
        timeout: 5m
  
  comment-pr:
    runs-on: ubuntu-latest
    needs: [setup-preview, deploy-preview]
    if: github.event.pull_request.draft == false && github.event.action != 'closed'
    steps:
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          const namespace = '${{ needs.setup-preview.outputs.namespace }}';
          const url = `https://pr-${prNumber}.dev-book-library.example.com`;
          
          const comment = `## 🚀 Preview Deployment Ready!
          
          Your PR has been deployed to a preview environment:
          
          - **URL**: ${url}
          - **Namespace**: ${namespace}
          - **Image**: pr-${prNumber}-${{ needs.setup-preview.outputs.short-sha }}
          
          The preview will be automatically cleaned up when the PR is closed.`;
          
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: comment
          });

  # Separate job that only runs on PR close
  cleanup-preview:
    name: Cleanup PR Preview
    runs-on: self-hosted
    if: github.event.action == 'closed'
    steps:
    - name: Generate preview info
      id: preview-info
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        NAMESPACE="book-library-pr-${PR_NUMBER}"
        RELEASE_NAME="book-library-pr-${PR_NUMBER}"
        echo "namespace=${NAMESPACE}" >> $GITHUB_OUTPUT
        echo "release-name=${RELEASE_NAME}" >> $GITHUB_OUTPUT
        
    - name: Delete preview deployment
      run: |
        helm uninstall ${{ steps.preview-info.outputs.release-name }} -n ${{ steps.preview-info.outputs.namespace }} || true
        kubectl delete namespace ${{ steps.preview-info.outputs.namespace }} --wait=false || true
  
  post-cleanup-pr-comment:
    runs-on: ubuntu-latest
    needs: cleanup-preview
    if: github.event.action == 'closed'
    steps:
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          
          const comment = `## 🧹 Preview Deployment Cleaned Up
          
          The preview deployment for PR #${prNumber} has been removed.`;
          
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: comment
          });